app:
  name: 'users-service-restful'
  host: 'http://localhost'
  port: 4000

db:
  redis:
    port: 6379
    host: 'localhost'
    password:

grpc:
  authentication:
    url: 'localhost:4010'
  payment:
    url: 'localhost:4010'
  recharge:
    url: 'localhost:4010'
  user:
    url: 'localhost:4010'
  wallet:
    url: 'localhost:4010'
